# -*- coding: utf-8 -*-
"""Copy of 01_featurize_with_GEE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16VppA4i_jeV5oMHqCt8fon6Sif7cECKj

#Instructions

This code will add satellite features to your site labels using Google Earth Engine. It will produce a series of .csv files that can be used to run tests.

This code no longer requires you to upload your labels file to GEE. You simiply need a GEE project already established. You can put the link to your GEE project and the labels .csv file directly into this code.

For best results, use the first code in this process ("Create Label Data", found in Github) for generating site labels.

This code is specifically for .csv files that do not have a Date column.

Before running this code, please scroll through and identify the locations that say "USER INPUT". There are multiple spots in the second block of cdoe where you must input your own file names and this code will not run correctly if you do not update these sections.

This code works for both state and federal labels.


#Important Note!
Once this code runs, it will generate a series of .csv files that save to the highest folder of your Google Drive.

You will see these .csv files slowly populate in your G Drive folder. This code will say "complete" before those files fully populate, so after completing this code you'll have to wait a few extra minutes to make sure all files are there. This is because GEE is working in the background to generate the results. The final line of this code will tell you how many files it intends to create, so you can check when GEE is done generating files. You can also track the progress of file generation in the GEE website interface.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install geemap

import geemap
import ee
import numpy as np
import os
from matplotlib import pyplot as plt
import pickle
import pandas as pd
import numpy as np
import shapely
import geopandas as gpd
import ee # earth engine
import folium
import datetime

from shapely.geometry import Point


DEBUG = False

from pathlib import Path
import shutil
import os



"""#User Input Section
Fill out the following two sections with your parameters anywhere that says "USER INPUT".
"""

##### ===== PARAMETER LOGIC ===== #####

### ACCEPTING ARGUMENTS FROM SHELL SCRIPT ###
# This is going into a dataframe that's saved as a csv so other scripts in the workflow can access it.
#
##### --- PARAMETERS --- ######
# We don't need to change parameters in this script anymore; they can be passed from the shell script.
# I will eventually make each of these a Series and then iterate through them so we can do multiple types at once/

### ACCEPTING ARGUMENTS FROM SHELL SCRIPT ###

### DIRECTORY ###
# This should almost never need to change
base_directory = "/projects/standard/rmyoung/shared/mosaiks"
scratch_directory = "/scratch.local" # experimental; will need to alter the shell script.
output_path = base_directory + "/output"


res = float(sys.argv[1])
location = str(sys.argv[2])
parcel_check = str(sys.argv[3]).lower() == "true"
zeroes = float(sys.argv[4])

res_string = str(res)

buff = (res*5)/10
round_value = (Decimal(res_string).as_tuple().exponent) + 1


#NAMING THE FILE
project_file = location + res_string.replace('.','_') + "_" + str(zeroes*100)

### SET DIRECTORIES ###
base_directory = "/projects/standard/rmyoung/shared/mosaiks"
output_path = base_directory + "/output"
scratch_directory = "/scratch.local"

#### ==== RETRIEVE COMBINED LABELS FROM LABEL CREATION STEP
project_file = location + res_string.replace('.','_') + "_" + str(zeroes*100)

#test_labels = output_path + "/" + project_file + "_combinedlabels" + file_suffix + ".csv"
test_labels = output_path + "/gee_test.csv"
test_labels = pd.read_csv(test_labels)


##### ===== GEE CONNECTION ===== #####
ee.Authenticate(auth_mode='localhost')
ee.Initialize(project=GEE_project) #insert GEE project name here





batch = test_labels

batch_gdf = gpd.GeoDataFrame(
    batch,
    geometry=gpd.points_from_xy(batch["lon"], batch["lat"]),
    crs="EPSG:4326")

# Convert to Earth Engine FeatureCollection
photo_fc = geemap.gdf_to_ee(batch_gdf, geodesic=True)

bands = np.arange(0,64).astype(str)
bands = ["A0" + x if len(x)==1 else "A"+x for x in bands]




# Combined reducer. Processes each band that we want to summarize over the given rectangle
reducer = (ee.Reducer.mean()
           .combine(ee.Reducer.percentile([0,10,20,30,40,50,60,70,80,90,100]), '', True))

total = len(batch_gdf)

points = photo_fc
points = points.toList(points.size())

if DEBUG:
    points = points.slice(0,1_000)

def make_rect(feature):
    lon = ee.Number(feature.get('lon'))
    lat = ee.Number(feature.get('lat'))

    rect = ee.Geometry.Rectangle([
        lon.subtract(buff), lat.subtract(buff),
        lon.add(buff), lat.add(buff)
    ])

    return ee.Feature(rect, feature.toDictionary())

batch_size = 100  # features per batch
if DEBUG:
    total = 1_000
num_batches = (total // batch_size) + 1

print(f"Total features: {total}, batches: {num_batches}")

today_date = datetime.date.today().strftime("%Y-%m-%d")

# Loop over batches and export each one
for i in range(num_batches):
    start = i * batch_size
    end = start + batch_size
    subset = points.slice(start,end)
    subset = ee.FeatureCollection(subset)
    fname = f'GEE_featurization_{today_date}_{i}_' + project_file #OPTIONAL USER INPUT TO CHANGE FILE NAME


    rects = subset.map(make_rect)

    collection = (ee.ImageCollection('GOOGLE/SATELLITE_EMBEDDING/V1/ANNUAL')
              .filterDate("2025-01-01") #Imagery is set to a specific year
              .filterBounds(rects)
             )

    composite = collection.select(bands).median() ## Should just be one image anyway. Median over time dimension

    stats_per_rect = composite.reduceRegions(
        collection=rects,
        reducer=reducer,
        crsTransform=crsTransform,
        crs='EPSG:4326',
    )

    ## Start download

    task = ee.batch.Export.table.toDrive(
        collection=stats_per_rect,
        description=f'GEE_Featurization_{today_date}_{i}_' + project_file, #OPTIONAL USER INPUT TO CHANGE DESCRIPTION
        fileNamePrefix=fname,
        fileFormat='CSV')

    task.start()
    print('Export task started:', task.status())
