# -*- coding: utf-8 -*-
"""random_forest_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QzRlC564w0vylox6e_0DWip6fSshAS8N

Uses the DecisionTreeClassifier.
* API Documentation on decision trees in scikit-learn [here](https://scikit-learn.org/stable/modules/tree.html#tree-classification)
* Documentation on DecisionTreeClassifier [here](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier.predict)
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install scikit-learn

import os
import numpy as np
import pandas as pd
import glob
from decimal import Decimal
import datetime

from shapely.geometry import box, Polygon, MultiPolygon, GeometryCollection


from scipy.linalg import LinAlgWarning
from sklearn.linear_model import RidgeCV
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt




debug: bool = True

###### --- PARAMETERS --- ######
# We don't need to change parameters in this script anymore; they can be passed from the shell script.
# I will eventually make each of these a Series and then iterate through them so we can do multiple types at once/

### ACCEPTING ARGUMENTS FROM SHELL SCRIPT ###

### DIRECTORY ###
# This should almost never need to change
base_directory = "/projects/standard/rmyoung/shared/mosaiks"
scratch_directory = "/scratch.local" # experimental; will need to alter the shell script.
output_path = base_directory + "/output"

if debug == True:
    res = 0.01
    location = "Minnesota"
    parcel_check = False
    zeroes = 1.0

else:
    res = float(sys.argv[1])
    location = str(sys.argv[2])
    parcel_check = str(sys.argv[3]).lower() == "true"
    zeroes = float(sys.argv[4])

res_string = str(res)

buff = (res*5)/10
round_value = (Decimal(res_string).as_tuple().exponent) + 1

if location == "Minnesota":
    poi_path = base_directory + "/raw/mn_superfund_spreadsheet.csv"
    parcel_path = base_directory + "/mn_parcels/mn_parcels.gpkg"

else:
    poi_path = base_directory + "/raw/federal_superfund_spreadsheet.csv"

#NAMING THE FILE
project_file = location + res_string.replace('.','_') + "_" + str(int(zeroes*100))


print("Resolution value is " + str(res) + " and the type is " + str(type(res)))
print("Location value is " + str(location) + " and the type is " + str(type(location)))
print("Parcel check value is " + str(parcel_check) + " and the type is " + str(type(parcel_check)))


##### ===== SET UP DATA FOR CLASSIFIER AND TESTING ===== #####

#------USER INPUT--------#

combined_labels_filename = base_directory + "/output/" + project_file + "_combinedlabels" + ".csv"

input_path = combined_labels_filename

'''
#input the folder path where your GEE .csv files are stored
folder_path = input_path
file_pattern = os.path.join(folder_path, 'GEE_featurization_2026-09-17_9_*.csv') #name pattern of files from GEE 	
file_list = glob.glob(file_pattern) 

df_list = [pd.read_csv(f) for f in file_list]

print(len(df_list))

full_df = pd.concat(df_list, ignore_index=True)

print(f"Final combined row count: {len(full_df)}")
full_df.head()
'''


training_labels = pd.read_csv(input_path)
training_labels.head()

sample_data = np.column_stack((
    training_labels['lat'],
    training_labels['lon']
))

label_data = training_labels['indicator']


##### ===== Sets up testing ===== #####
X = sample_data
y = label_data

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Sample Data shape is " + str(sample_data.shape))
print("Label Data shape is " + str(label_data.shape))


##### ===== CREATE THE CLASSIFIER ===== #####


from sklearn.linear_model import LogisticRegression

# Initialize the classifier
clf = RandomForestClassifier()

from sklearn.metrics import (
    roc_auc_score, accuracy_score, precision_score,
    log_loss, RocCurveDisplay, classification_report
)
import matplotlib.pyplot as plt

# 1. Fit the model on training data
clf = clf.fit(X_train, y_train)

# 2. Generate Predictions on the Test Set
# Probabilities are needed for ROC and Log Loss
y_probs = clf.predict_proba(X_test)[:, 1]
# Classes are needed for Accuracy and Precision
y_pred = clf.predict(X_test)



# 3. Calculate the "Big Four" Metrics
auc_val = roc_auc_score(y_test, y_probs)
acc_val = accuracy_score(y_test, y_pred)
prec_val = precision_score(y_test, y_pred)
loss_val = log_loss(y_test, y_probs)

# 4. Print the Performance Dashboard
print("--- Test Set Performance ---")
print(classification_report(y_test, y_pred))
print(f"{'ROC-AUC:':<12} {auc_val:.4f}")
print(f"{'Accuracy:':<12} {acc_val:.4f}")
print(f"{'Precision:':<12} {prec_val:.4f}")
print(f"{'Log Loss:':<12} {loss_val:.4f}")

# 5. Generate the ROC Curve Plot
fig, ax = plt.subplots(figsize=(7, 7))
RocCurveDisplay.from_predictions(
    y_test,
    y_probs,
    name="Test Set ROC",
    curve_kwargs={"color": "blue", "linewidth": 2},
    ax=ax,
    plot_chance_level=True
)

ax.set_title(f"ROC Curve (AUC = {auc_val:.3f})")
plt.grid(alpha=0.3)

#------USER INPUT--------#
#Save image to your Drive folder: edit the output folder path and file name as needed
today_date = datetime.date.today().strftime("%Y-%m-%d")
output_folder = output_path #output folder path

output_plot_filename = output_path + "/ROC_curve_" + project_file + ".pdf" #rename as needed

plt.savefig(output_plot_filename, dpi=300, bbox_inches='tight')

#Save text results to Drive folder
output_text_filename = output_path + "/performance_results_" + project_file + ".txt" #rename as needed
with open(output_text_filename, 'w') as f:
    f.write("--- Test Set Performance ---")
    f.write(classification_report(y_test, y_pred))
    f.write(f"{'ROC-AUC:':<12} {auc_val:.4f}\n")
    f.write(f"{'Accuracy:':<12} {acc_val:.4f}\n")
    f.write(f"{'Precision:':<12} {prec_val:.4f}\n")
    f.write(f"{'Log Loss:':<12} {loss_val:.4f}\n")


plt.show()


