# -*- coding: utf-8 -*-
"""random_forest_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QzRlC564w0vylox6e_0DWip6fSshAS8N

Uses the DecisionTreeClassifier.
* API Documentation on decision trees in scikit-learn [here](https://scikit-learn.org/stable/modules/tree.html#tree-classification)
* Documentation on DecisionTreeClassifier [here](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier.predict)
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install scikit-learn

import os
import numpy as np
import pandas as pd

from shapely.geometry import box, Polygon, MultiPolygon, GeometryCollection
from sklearn import tree

debug: bool = True

###### --- PARAMETERS --- ######
# We don't need to change parameters in this script anymore; they can be passed from the shell script.
# I will eventually make each of these a Series and then iterate through them so we can do multiple types at once/

### ACCEPTING ARGUMENTS FROM SHELL SCRIPT ###

### DIRECTORY ###
# This should almost never need to change
base_directory = "/projects/standard/rmyoung/shared/mosaiks"
scratch_directory = "/scratch.local" # experimental; will need to alter the shell script.
output_path = base_directory + "/output"

if debug == True:
    res = 0.1
    location = "Minnesota"
    parcel_check = False
    zeroes = 1.0

else:
    res = float(sys.argv[1])
    location = str(sys.argv[2])
    parcel_check = str(sys.argv[3]).lower() == "true"
    zeroes = float(sys.argv[4])

res_string = str(res)

buff = (res*5)/10
round_value = (Decimal(res_string).as_tuple().exponent) + 1

if location == "Minnesota":
    poi_path = base_directory + "/raw/mn_superfund_spreadsheet.csv"
    parcel_path = base_directory + "/mn_parcels/mn_parcels.gpkg"

else:
    poi_path = base_directory + "/raw/federal_superfund_spreadsheet.csv"

#NAMING THE FILE
project_file = location + res_string.replace('.','_') + "_" + str(zeroes*100)


print("Resolution value is " + str(res) + " and the type is " + str(type(res)))
print("Location value is " + str(location) + " and the type is " + str(type(location)))
print("Parcel check value is " + str(parcel_check) + " and the type is " + str(type(parcel_check)))





test_labels = pd.read_csv(input_path)
test_labels.head()

sample_size = len(test_labels)//2

ran_indices = np.random.choice(len(test_labels), size=sample_size, replace=False)

sample_data = np.column_stack((
    test_labels['lat'].iloc[ran_indices],
    test_labels['lon'].iloc[ran_indices]
))



label_data = test_labels['indicator'].iloc[ran_indices]

print(sample_data.shape)

# ============================== #
# testing on out of sample locations

all_indices = np.arange(0,len(test_labels))

test_indices = np.delete(all_indices, ran_indices)

sharing_check = set(test_indices).isdisjoint(set(ran_indices))
print("Training sample and testing data don't share sites is: " + str(sharing_check))

tryout_sample = np.column_stack((
    test_labels['lat'].iloc[test_indices],
    test_labels['lon'].iloc[test_indices]
))

#tryout_labels = test_labels['indicator'].iloc[test_indices]

print(tryout_sample.shape)

loc_classifier = tree.DecisionTreeClassifier()
loc_classifier = loc_classifier.fit(sample_data, label_data)

test_answers = loc_classifier.predict(tryout_sample)

print(test_answers)

answers_dictionary = {
    'lat': tryout_sample[:,0],
    'lon': tryout_sample[:,1],
    'forest indicator': test_answers,
    'actual indicator': test_labels['indicator'].iloc[test_indices]
}



answers = pd.DataFrame(answers_dictionary)

print(answers)
answers.to_csv(output_path, index=False)

forest_indicator_counts = answers['forest indicator'].value_counts()
actual_indicator_counts = answers['actual indicator'].value_counts()

print(forest_indicator_counts)
print(actual_indicator_counts)

"""Get output [here](https://drive.google.com/drive/folders/1Gc-wHjrz6HrfFUj5x8myGvnPfFeElGC4)"""